service: my-ser-starter # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs6.10
  versionFunctions: false

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can define service wide environment variables here
environment:
  variable1: ${opt:stage}

# you can add packaging information here
package:
  include:
    - public/**
    - build/**
    # - include-me-dir/**
  exclude:
    - src/**
    - .config/**
    -  config/**
  # excludeDevDependencies: false

functions:
  api:
    handler: build/handler.express
    events:
      - http: ANY {proxy+}
  # test:
  #   handler: handler.hello
  #   events:
  #     - http:
  #         path: hello
  #         method: get