version: 2
jobs:
  build:
    working_directory: ~/my_ser_starter
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: npm run build
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/my_ser_starter

  test:
    working_directory: ~/my_ser_starter
    docker:
      - image: circleci/node:8
    steps:
      - run:  
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run:
          name: Test
          command: npm test
  deploy-dev:
    working_directory: ~/my_ser_starter
    docker:
      - image: circleci/node:8
    steps:
      - run:  
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run:
          name: Dev deploy
          command: npm run deploy -- --stage dev
  deploy-prod:
    working_directory: ~/my_ser_starter
    docker:
      - image: circleci/node:8
    steps:
      - run:  
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run:
          name: prod deploy
          command: npm run deploy -- --stage prod
      - store_artifacts:
          path: /.serverless
          destination: build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
              - build
      - deploy-dev:
          requires:
              - test
      - deploy-prod:
          requires:
              - deploy-dev