version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/my_ser_starter
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test
  deploy:
    docker:
      - image: circleci/node:8
    working_directory: ~/my_ser_starter
     steps:
        - run:
            name: Dev deploy
            command: npm run deploy -- --stage dev
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master