version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/my_react_starter
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm test