version: 2
jobs:
  build:
    working_directory: ~/my_ser_starter
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build
          command: npm run build
      - run:
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - save_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
          paths:
            - ~/my_ser_starter

  test:
    working_directory: ~/my_ser_starter
    docker:
      - image: circleci/node:8
    steps:
      - run:  
          name: save SHA to a file
          command: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          keys:
            - v1-repo-{{ checksum ".circle-sha" }}
      - run:
          name: list
          command: ls -lh
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
              - build

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:8
#     working_directory: ~/my_ser_starter
#     steps:
#       - checkout
#       - run:
#           name: Install dependencies
#           command: yarn
#       - run:
#           name: Build
#           command: npm run build
#       - run:
#           name: Test
#           command: npm test
#   deploy:
#     steps:
#       - run:
#           name: Dev deploy
#           command: npm run deploy -- --stage dev
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master